spring:
    datasource:
        username: root
        password: 
        url: jdbc:mysql://localhost:3306/workshop
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        default-property-inclusion: NON_NULL